### PR TITLE
ClasspathElementDir review adjustments

### PR DESCRIPTION
**Pull request by attilapuskas**
Based on the following comments:
https://github.com/classgraph/classgraph/pull/850#discussion_r1570337208
https://github.com/classgraph/classgraph/pull/850#discussion_r1570348184

### CODE REVIEW

**Comment by lukehutch** [comment]
LGTM. Thanks!

**Comment by lukehutch** [comment]
Released in 4.8.172.

**Comment by attilapuskas** [comment]
Thanks!
Do you know by any chance why build (windows-latest, 15 & 18) have failed? They give the results in different order, but I have no idea how the commits could cause such a thing.

**Comment by lukehutch** [comment]
I opened a bug about that. There's some nondeterminism in the classpath resolution order which is not supposed to be there (the order is supposed to be deterministic, despite parallel scanning). I don't know what could cause that, and it's going to be a hard bug to get to the bottom of. I don't have the time to look into it right now. But if you look at the failing test, you might be able to figure it out.

The issue occurs when a classpath element adds additional classpath elements to the scan, partway through the scan. Specifically, when a manifest has a Class-Path entry.

**Comment by attilapuskas** [comment]
I see, thanks for the detailed explanation!

**Pull request merged**
