### PR TITLE
Support for java - loggers #294

### PR DESCRIPTION
**Pull request by gitmotte**
fix for:  https://github.com/classgraph/classgraph/issues/294#issuecomment-454226138

"if any of the ClassGraph tests that run before LogNodeTest enable
verbose logging by calling .verbose() before .scan(), then when
LogNodeTest runs, its test fails. Specifically systemErrMessages ends up
empty"

> add a ConsoleHandler after setting System.setErr specific for this
testcase and remove it afterwards.

> remove specific logging.properties - default logging.properties of jre
will be enough.

### CODE REVIEW

**Comment by gitmotte** [comment]
The command "~/bin/install-jdk.sh --target "/home/travis/openjdk11" --workspace "/home/travis/.cache/install-jdk" --feature "11" --license "GPL" --cacerts" failed and exited with 7 during .

don't know why this fails, @lukehutch do you have an idea?

**Comment by gitmotte** [comment]
Did a openjdk11 build on windows with success.

**Comment by lukehutch** [comment]
> don't know why this fails, @lukehutch do you have an idea?

I see these failures in Travis all the time. They are transient failures. I don't know what the issue is, but it's not a problem with the build itself.

**Comment by lukehutch** [comment]
PS many thanks for submitting a solution right away! See question above about System.setErr, but otherwise, looks good to me.

**Comment by lukehutch** [comment]
@gitmotte Awesome, thanks so much for these fixes! Much appreciated.

**Comment by gitmotte** [comment]
:) thank you, too, for this great library!

**Pull request merged**
