### PR TITLE
Add javadoc link

### PR DESCRIPTION
**Pull request by johnou**

### CODE REVIEW

**Comment by lukehutch** [comment]
Good addition, thanks. I have the javadoc.io link below, but badge form is good too.

**Comment by johnou** [comment]
@lukehutch yeah noted that, I'm a fan of the badges, look good even on mobile.

**Comment by johnou** [comment]
I think you just need a logo for the project now ;)

**Comment by lukehutch** [comment]
Yeah, they do look good, I agree. And good suggestion on the project logo. The default GitHub "space invaders" logo is a bit jarring :-)

**Comment by lukehutch** [comment]
@johnou I added a logo. It's highly cliche', but what do you think?

**Comment by johnou** [comment]
Tbh I like it, gives the project a more polished feel.

**Pull request merged**
